vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        GallerieImage:
            uri_prefix: /public/uploads
            upload_destination: '%kernel.project_dir%/public/images/gallery'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer  
